### ISSUE TITLE
Nice homepage, do you mind remove my GCP key?

### ISSUE THREAD

**Issue by TianxiaoHu** [mud2man/mud2man.github.io#1]
Hi! I noticed this nice homepage by an email from GCP this morning. I guess you are using my GCP key for mistake here -- if you are not using Google Map API do you mind remove this line from your repo?

https://github.com/mud2man/mud2man.github.io/blob/3fa93c5a5bc2463a18907ebb178e1825ba0b843b/index.html#L15

Thanks,
Tianxiao

**Comment by mud2man** [comment]
Hi Tianxiao 

Sorry about the mistake. Already removed it. 

Best regards,
Namo
